name: Web

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12.19.0'
    - name: Get Submodules
      run: git submodule update --init --recursive
    - name: Install armsdk
      run: |
        git clone --recursive https://github.com/armory3d/armsdk.git
    - name: Build
      run: node --unhandled-rejections=strict armsdk/Kha/make.js -t html5
